---
- hosts: remote_servers

  tasks: 
    
    - name: Check old version existance
      shell: "which docker"
      register: result
      ignore_errors: true

    - name: Check result
      debug:
        msg: Docker is already installed on {{result.stdout}}
      when: result.rc == 0  
    
    - name: Remove old installed version
      apt:
        name: "{{ item }}"
        state: absent
      loop:
        - docker 
        - docker-engine 
        - docker.io 
        - containerd 
        - runc
       
    - name: Purge 
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      loop:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io 

    - name: Remove old files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/docker
        - /var/lib/containerd 
    
    - name: Install prerequisites packages 
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - apt-transport-https 
        - ca-certificates 
        - curl 
        - gnupg 
        - lsb-release 
    
   # - name: Get get-docker.sh 
   #   shell: curl -fsSL https://get.docker.com -o get-docker.sh
  

   # - name: Install Docker via Script 
   #   shell: sh get-docker.sh
   
      
    
    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      
  
    - name: Set up the stable repository
      apt_repository: 
        repo: deb https://download.docker.com/linux/ubuntu {{ansible_distribution_release | lower}} stable
        state: present
      
                   
    - name: Install docker-engine packages 
      apt:
        name: "{{ item }}"
        state: present 
        update_cache: true
      loop:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io
      
    
    - name : Set docker user 
      group:
        name: docker

    - name: Join user to docker group
      user:
        name: "{{ansible_env.SUDO_USER}}"
        groups: docker
        append: yes

    - name: Install pip3
      apt:
        name: python3-pip

    - name: Install Docker SDK for Python
      pip:
        name: docker

    - name: Pull default docker image
      docker_image:
        name: hello-world
        source: pull
      
    - name: Run default docker container
      docker_container:
        name: hello-world
        image: hello-world
        command: sleep 10m
    
  vars_files:
    - secret.yaml


  